import { createClient } from "npm:@supabase/supabase-js@2";
import { sendGmailRawEmail } from "../_shared/gmail.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const STAFF_ROLES = new Set(["super_admin", "admin", "supervisor", "staff"]);
const CUSTOMER_PERMISSIONS = {
  rescue: "none",
  schedule: "none",
  catalog_tires: "none",
  catalog_rims: "none",
  orders: "none",
  invoices: "none",
  customers: "none",
  accounts: "none",
};

type SupabaseClient = ReturnType<typeof createClient<any>>;

function jsonResponse(body: unknown, status = 200) {
  return Response.json(body, { status, headers: corsHeaders });
}

function normalizeText(value: unknown) {
  return String(value ?? "").trim();
}

function isValidEmail(value: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

function publicSiteUrl() {
  const candidates = [
    Deno.env.get("PUBLIC_SITE_URL"),
    Deno.env.get("SITE_URL"),
    Deno.env.get("BOOKING_SITE_URL"),
  ];

  for (const candidate of candidates) {
    const value = String(candidate ?? "").trim().replace(/\/+$/, "");
    if (!value) continue;

    try {
      const url = new URL(value);
      const host = url.hostname.toLowerCase();
      if (url.protocol === "https:" && host !== "localhost" && host !== "127.0.0.1" && host !== "0.0.0.0") {
        return value;
      }
    } catch {
      // Ignore invalid deployment environment values.
    }
  }

  return "https://mitra-auto.fi";
}

function customerPortalUrl() {
  const explicit = normalizeText(Deno.env.get("CUSTOMER_PORTAL_URL") ?? Deno.env.get("PUBLIC_CUSTOMER_PORTAL_URL"));
  if (explicit) {
    try {
      const url = new URL(explicit);
      if (url.protocol === "https:") return explicit.replace(/\/+$/, "");
    } catch {
      // Fall back to the public site account route.
    }
  }

  return `${publicSiteUrl()}/account`;
}

function buildPortalPasswordSetupLink(redirectTo: string, tokenHash: string) {
  const url = new URL(redirectTo);
  url.searchParams.set("type", "recovery");
  url.searchParams.set("token_hash", tokenHash);
  return url.toString();
}

function randomPassword() {
  const buffer = crypto.getRandomValues(new Uint8Array(32));
  return Array.from(buffer).map((item) => item.toString(16).padStart(2, "0")).join("");
}

function buildSetupEmailHtml(actionLink: string, displayName: string) {
  const greeting = displayName ? `Hello ${displayName},` : "Hello,";
  return `
    <div style="font-family:Arial,sans-serif;line-height:1.6;color:#1f2937">
      <h2 style="margin:0 0 16px">Mitra Auto customer account</h2>
      <p>${greeting}</p>
      <p>Your Mitra Auto customer account is ready. Use the button below to set your password and open your customer portal.</p>
      <p>
        <a href="${actionLink}" style="display:inline-block;background:#ff6b35;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:6px">
          Set password
        </a>
      </p>
      <p>Inside the portal you can view your vehicles, appointments, service history, reminders, and customer benefits.</p>
      <p>If you were not expecting this account, contact Mitra Auto immediately.</p>
      <p style="font-size:12px;color:#6b7280">This link is generated by Mitra Auto account security.</p>
    </div>
  `.trim();
}

async function findAuthUserIdByEmail(serviceClient: SupabaseClient, email: string) {
  for (let page = 1; page <= 20; page += 1) {
    const { data, error } = await serviceClient.auth.admin.listUsers({ page, perPage: 1000 });
    if (error) throw error;

    const user = data.users.find((candidate) => candidate.email?.toLowerCase() === email);
    if (user?.id) return user.id;
    if (data.users.length < 1000) break;
  }

  return null;
}

async function ensureCustomerManager(request: Request) {
  const authHeader = request.headers.get("Authorization");
  if (!authHeader) {
    throw new Error("Unauthenticated");
  }

  const userClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    { global: { headers: { Authorization: authHeader } } },
  );

  const { data: { user }, error: userError } = await userClient.auth.getUser();
  if (userError || !user) {
    throw new Error("Unauthenticated");
  }

  const { data: canManageCustomers, error: permissionError } = await userClient.rpc("cms_has_permission", {
    p_module: "customers",
    p_action: "write",
  });

  if (permissionError || canManageCustomers !== true) {
    throw new Error("Forbidden");
  }

  return { user, userClient };
}

async function getCustomerForAccount(
  serviceClient: SupabaseClient,
  customerId: string,
) {
  const { data, error } = await serviceClient
    .from("customers")
    .select("id, primary_email, full_name, status, account_id")
    .eq("id", customerId)
    .maybeSingle();

  if (error) throw new Error(error.message);
  if (!data || ["deleted", "merged"].includes(String(data.status))) {
    throw new Error("Customer not found");
  }

  return data as {
    id: string;
    primary_email: string | null;
    full_name: string | null;
    status: string;
    account_id: string | null;
  };
}

async function assertCustomerEmailPolicy(
  userClient: SupabaseClient,
  customerEmail: string | null,
  accountEmail: string,
) {
  const normalizedCustomerEmail = normalizeText(customerEmail).toLowerCase();
  if (!normalizedCustomerEmail || normalizedCustomerEmail === accountEmail) return;

  const { data: isSuperAdmin, error } = await userClient.rpc("cms_is_super_admin");
  if (error || isSuperAdmin !== true) {
    throw new Error("Customer account email must match the customer primary email. Super admin override required.");
  }
}

async function assertAccountCanBeLinked(
  serviceClient: SupabaseClient,
  customerId: string,
  accountId: string,
) {
  const { data: linkedCustomer, error: linkedError } = await serviceClient
    .from("customers")
    .select("id")
    .eq("account_id", accountId)
    .not("status", "in", "(deleted,merged)")
    .neq("id", customerId)
    .maybeSingle();

  if (linkedError) throw new Error(linkedError.message);
  if (linkedCustomer?.id) {
    throw new Error("Auth account is already linked to another customer");
  }

  const { data: profile, error: profileError } = await serviceClient
    .from("profiles")
    .select("role, account_status")
    .eq("id", accountId)
    .maybeSingle();

  if (profileError) throw new Error(profileError.message);
  if (profile?.role && STAFF_ROLES.has(String(profile.role)) && String(profile.account_status ?? "active") !== "deleted") {
    throw new Error("This email belongs to a CMS staff account and cannot be used as a customer portal account");
  }
}

async function createOrFindCustomerAuthUser(
  serviceClient: SupabaseClient,
  email: string,
  displayName: string,
) {
  const { data, error } = await serviceClient.auth.admin.createUser({
    email,
    password: randomPassword(),
    email_confirm: true,
    user_metadata: {
      display_name: displayName || null,
      role: "customer",
    },
    app_metadata: {
      role: "customer",
    },
  });

  if (data.user?.id) {
    return { userId: data.user.id, existingUser: false };
  }

  if (error && !/already|registered|exists/i.test(error.message ?? "")) {
    throw error;
  }

  const userId = await findAuthUserIdByEmail(serviceClient, email);
  if (!userId) {
    throw new Error("Auth user could not be created or resolved by email");
  }

  return { userId, existingUser: true };
}

async function upsertCustomerProfile(
  serviceClient: SupabaseClient,
  userId: string,
  displayName: string,
) {
  const { error } = await serviceClient
    .from("profiles")
    .upsert({
      id: userId,
      role: "customer",
      display_name: displayName || null,
      cms_permissions: CUSTOMER_PERMISSIONS,
      account_status: "active",
      account_hidden: false,
      updated_at: new Date().toISOString(),
    }, { onConflict: "id" });

  if (error) throw new Error(error.message);

  await serviceClient.auth.admin.updateUserById(userId, {
    user_metadata: {
      display_name: displayName || null,
      role: "customer",
    },
    app_metadata: {
      role: "customer",
    },
  });
}

async function linkCustomer(
  serviceClient: SupabaseClient,
  actorId: string,
  customerId: string,
  userId: string,
  email: string,
  eventType: string,
) {
  const now = new Date().toISOString();
  const { error: updateError } = await serviceClient
    .from("customers")
    .update({
      account_id: userId,
      portal_enabled: true,
      portal_invited_at: now,
      updated_by: actorId,
      updated_at: now,
    })
    .eq("id", customerId);

  if (updateError) throw new Error(updateError.message);

  const { error: eventError } = await serviceClient.from("customer_events").insert({
    customer_id: customerId,
    actor_id: actorId,
    event_type: eventType,
    details: {
      account_id: userId,
      email,
      role: "customer",
      portal_enabled: true,
    },
  });

  if (eventError) throw new Error(eventError.message);
}

async function sendActivationLink(
  serviceClient: SupabaseClient,
  actorId: string,
  customerId: string,
  userId: string,
  email: string,
  displayName: string,
) {
  const redirectTo = customerPortalUrl();
  const { data: linkData, error: linkError } = await serviceClient.auth.admin.generateLink({
    type: "recovery",
    email,
  });

  if (linkError || !linkData?.properties?.hashed_token) {
    throw linkError ?? new Error("Password setup link could not be generated");
  }

  const actionLink = buildPortalPasswordSetupLink(redirectTo, linkData.properties.hashed_token);
  const subject = "Mitra Auto customer account setup";
  const text = [
    "Mitra Auto customer account",
    "",
    displayName ? `Hello ${displayName},` : "Hello,",
    "",
    "Your Mitra Auto customer account is ready.",
    "Use this link to set your password and open your customer portal:",
    actionLink,
    "",
    "Inside the portal you can view your vehicles, appointments, service history, reminders, and customer benefits.",
    "",
    "If you were not expecting this account, contact Mitra Auto immediately.",
  ].join("\n");

  await sendGmailRawEmail({
    toEmail: email,
    toName: displayName,
    subject,
    text,
    html: buildSetupEmailHtml(actionLink, displayName),
  });

  await serviceClient.from("customer_events").insert({
    customer_id: customerId,
    actor_id: actorId,
    event_type: "customer_portal_activation_link_sent",
    details: {
      account_id: userId,
      email,
      provider: "gmail",
      redirect_to: redirectTo,
    },
  });
}

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (request.method !== "POST") {
    return jsonResponse({ error: "Method not allowed" }, 405);
  }

  try {
    const { user: actor, userClient } = await ensureCustomerManager(request);
    const body = await request.json().catch(() => ({}));
    const action = normalizeText(body?.action) || "create_or_link";
    const customerId = normalizeText(body?.customerId);
    const requestedEmail = normalizeText(body?.email).toLowerCase();

    if (!customerId) {
      return jsonResponse({ error: "Customer ID is required" }, 400);
    }

    const serviceClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } },
    );

    const customer = await getCustomerForAccount(serviceClient, customerId);
    const email = requestedEmail || normalizeText(customer.primary_email).toLowerCase();
    const displayName = normalizeText(body?.displayName) || normalizeText(customer.full_name);

    if (!email || !isValidEmail(email)) {
      return jsonResponse({ error: "Valid customer email is required" }, 400);
    }

    await assertCustomerEmailPolicy(userClient, customer.primary_email, email);

    if (action === "send_activation_link") {
      const userId = customer.account_id || await findAuthUserIdByEmail(serviceClient, email);
      if (!userId) {
        return jsonResponse({ error: "Customer portal account has not been created yet" }, 400);
      }

      await assertAccountCanBeLinked(serviceClient, customerId, userId);
      await upsertCustomerProfile(serviceClient, userId, displayName);
      if (!customer.account_id) {
        await linkCustomer(serviceClient, actor.id, customerId, userId, email, "customer_portal_account_linked");
      }
      await sendActivationLink(serviceClient, actor.id, customerId, userId, email, displayName);

      return jsonResponse({ ok: true, userId, activationEmailSent: true });
    }

    if (action !== "create_or_link") {
      return jsonResponse({ error: "Unknown action" }, 400);
    }

    const { userId, existingUser } = await createOrFindCustomerAuthUser(serviceClient, email, displayName);
    await assertAccountCanBeLinked(serviceClient, customerId, userId);
    await upsertCustomerProfile(serviceClient, userId, displayName);
    await linkCustomer(
      serviceClient,
      actor.id,
      customerId,
      userId,
      email,
      existingUser ? "customer_portal_account_attached_existing_auth_user" : "customer_portal_account_created",
    );
    await sendActivationLink(serviceClient, actor.id, customerId, userId, email, displayName);

    return jsonResponse({ ok: true, userId, existingUser, activationEmailSent: true });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Customer portal account action failed";
    const status = message === "Unauthenticated" ? 401 : message === "Forbidden" ? 403 : 400;
    return jsonResponse({ error: message }, status);
  }
});
