import { createClient } from "npm:@supabase/supabase-js@2";
import { sendGmailRawEmail } from "../_shared/gmail.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function jsonResponse(body: unknown, status = 200) {
  return Response.json(body, { status, headers: corsHeaders });
}

function normalizeEmail(value: unknown) {
  return String(value ?? "").trim().toLowerCase();
}

function passwordSetupUrl() {
  const explicitSetupUrl = String(Deno.env.get("CMS_PASSWORD_SETUP_URL") ?? "").trim();
  if (explicitSetupUrl) return explicitSetupUrl.replace(/\/+$/, "");

  const supabaseUrl = String(Deno.env.get("SUPABASE_URL") ?? "").trim().replace(/\/+$/, "");
  if (supabaseUrl) return `${supabaseUrl}/functions/v1/cms_password_setup`;

  const candidates = [
    Deno.env.get("PUBLIC_SITE_URL"),
    Deno.env.get("SITE_URL"),
    Deno.env.get("BOOKING_SITE_URL"),
  ];

  for (const candidate of candidates) {
    const value = String(candidate ?? "").trim().replace(/\/+$/, "");
    if (!value) continue;

    try {
      const url = new URL(value);
      const host = url.hostname.toLowerCase();
      if (url.protocol === "https:" && host !== "localhost" && host !== "127.0.0.1" && host !== "0.0.0.0") {
        return `${value}/cms/password-setup`;
      }
    } catch {
      // Ignore invalid deployment environment values.
    }
  }

  return "https://www.mitra-auto.fi/cms/password-setup";
}

function buildPasswordSetupLink(setupUrl: string, tokenHash: string) {
  const url = new URL(setupUrl);
  url.searchParams.set("type", "recovery");
  url.searchParams.set("token_hash", tokenHash);
  return url.toString();
}

function buildHtml(actionLink: string) {
  return `
    <div style="font-family:Arial,sans-serif;line-height:1.6;color:#1f2937">
      <h2 style="margin:0 0 16px">Mitra Auto password reset</h2>
      <p>Use the button below to change your password.</p>
      <p>
        <a href="${actionLink}" style="display:inline-block;background:#ff6b35;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:6px">
          Change password
        </a>
      </p>
      <p>If you did not request this, ignore this email.</p>
      <p style="font-size:12px;color:#6b7280">This link is generated by Mitra Auto account security.</p>
    </div>
  `.trim();
}

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (request.method !== "POST") {
    return jsonResponse({ error: "Method not allowed" }, 405);
  }

  try {
    const body = await request.json().catch(() => ({}));
    const email = normalizeEmail(body?.email);

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return jsonResponse({ ok: true });
    }

    const serviceClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } },
    );

    const { data: userList, error: userListError } = await serviceClient.auth.admin.listUsers({
      page: 1,
      perPage: 1000,
    });

    if (userListError) throw userListError;

    const user = userList.users.find((candidate) => candidate.email?.toLowerCase() === email);
    if (!user?.id) {
      return jsonResponse({ ok: true });
    }

    const { data: profile, error: profileError } = await serviceClient
      .from("profiles")
      .select("id, role, account_status, display_name")
      .eq("id", user.id)
      .maybeSingle();

    if (profileError) throw profileError;

    if (profile?.account_status === "deleted") {
      return jsonResponse({ ok: true });
    }

    const setupUrl = passwordSetupUrl();
    const { data: linkData, error: linkError } = await serviceClient.auth.admin.generateLink({
      type: "recovery",
      email,
    });

    if (linkError || !linkData?.properties?.hashed_token) {
      throw linkError ?? new Error("Could not generate password recovery link");
    }

    const actionLink = buildPasswordSetupLink(setupUrl, linkData.properties.hashed_token);
    const subject = "Mitra Auto password reset";
    const text = [
      "Mitra Auto password reset",
      "",
      "Use this link to change your password:",
      actionLink,
      "",
      "If you did not request this, ignore this email.",
    ].join("\n");

    await sendGmailRawEmail({
      toEmail: email,
      toName: String(profile?.display_name ?? ""),
      subject,
      text,
      html: buildHtml(actionLink),
    });

    if (profile?.id) {
      await serviceClient.from("cms_account_events").insert({
        target_profile_id: user.id,
        actor_id: user.id,
        event_type: "account_password_recovery_sent",
        details: {
          provider: "gmail",
          email,
        },
      });
    }

    return jsonResponse({ ok: true });
  } catch (error) {
    console.error("CMS account recovery failed", error);
    return jsonResponse({ error: error instanceof Error ? error.message : "Recovery failed" }, 400);
  }
});
