import { createClient } from "npm:@supabase/supabase-js@2";
import { sendGmailRawEmail } from "../_shared/gmail.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const ALLOWED_ROLES = new Set(["super_admin", "admin", "supervisor", "staff", "customer", "user", "disabled"]);
const ALLOWED_PERMISSIONS = new Set(["none", "read", "read_write"]);
const CMS_MODULES = ["rescue", "schedule", "catalog_tires", "catalog_rims", "orders", "invoices", "customers", "accounts"];
type ServiceClient = ReturnType<typeof createClient<any>>;

function jsonResponse(body: unknown, status = 200) {
  return Response.json(body, { status, headers: corsHeaders });
}

function normalizeText(value: unknown) {
  return String(value ?? "").trim();
}

function normalizeRole(value: unknown) {
  const role = normalizeText(value);
  return ALLOWED_ROLES.has(role) ? role : "supervisor";
}

function normalizePermissions(value: unknown) {
  const source = value && typeof value === "object" ? value as Record<string, unknown> : {};
  return CMS_MODULES.reduce<Record<string, string>>((permissions, module) => {
    const permission = normalizeText(source[module]);
    permissions[module] = ALLOWED_PERMISSIONS.has(permission) ? permission : "none";
    return permissions;
  }, {});
}

function defaultPermissionsForRole(role: string) {
  const permissions = normalizePermissions({});

  if (role === "super_admin" || role === "admin") {
    for (const module of CMS_MODULES) {
      permissions[module] = "read_write";
    }
    return permissions;
  }

  if (role === "supervisor" || role === "staff") {
    permissions.customers = "read_write";
  }

  return permissions;
}

function passwordSetupUrl() {
  const explicitSetupUrl = String(Deno.env.get("CMS_PASSWORD_SETUP_URL") ?? "").trim();
  if (explicitSetupUrl) return explicitSetupUrl.replace(/\/+$/, "");

  const supabaseUrl = String(Deno.env.get("SUPABASE_URL") ?? "").trim().replace(/\/+$/, "");
  if (supabaseUrl) return `${supabaseUrl}/functions/v1/cms_password_setup`;

  const candidates = [
    Deno.env.get("PUBLIC_SITE_URL"),
    Deno.env.get("SITE_URL"),
    Deno.env.get("BOOKING_SITE_URL"),
  ];

  for (const candidate of candidates) {
    const value = String(candidate ?? "").trim().replace(/\/+$/, "");
    if (!value) continue;

    try {
      const url = new URL(value);
      const host = url.hostname.toLowerCase();
      if (url.protocol === "https:" && host !== "localhost" && host !== "127.0.0.1" && host !== "0.0.0.0") {
        return `${value}/cms/password-setup`;
      }
    } catch {
      // Ignore invalid deployment environment values.
    }
  }

  return "https://www.mitra-auto.fi/cms/password-setup";
}

function buildPasswordSetupLink(setupUrl: string, tokenHash: string) {
  const url = new URL(setupUrl);
  url.searchParams.set("type", "recovery");
  url.searchParams.set("token_hash", tokenHash);
  return url.toString();
}

function temporaryPassword() {
  const bytes = new Uint8Array(24);
  crypto.getRandomValues(bytes);
  const token = btoa(String.fromCharCode(...bytes)).replace(/[+/=]/g, "");
  return `${token}Aa1!`;
}

function buildSetupEmailHtml(actionLink: string, role: string) {
  return `
    <div style="font-family:Arial,sans-serif;line-height:1.6;color:#1f2937">
      <h2 style="margin:0 0 16px">Mitra Auto CMS account</h2>
      <p>Your Mitra Auto CMS account has been created with role <strong>${role}</strong>.</p>
      <p>Use the button below to set your password and open the CMS.</p>
      <p>
        <a href="${actionLink}" style="display:inline-block;background:#ff6b35;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:6px">
          Set password
        </a>
      </p>
      <p>If you were not expecting this account, contact Mitra Auto immediately.</p>
      <p style="font-size:12px;color:#6b7280">This link is generated by Mitra Auto account security.</p>
    </div>
  `.trim();
}

async function findAuthUserIdByEmail(serviceClient: ServiceClient, email: string) {
  for (let page = 1; page <= 20; page += 1) {
    const { data, error } = await serviceClient.auth.admin.listUsers({ page, perPage: 1000 });
    if (error) throw error;

    const user = data.users.find((candidate) => candidate.email?.toLowerCase() === email);
    if (user?.id) return user.id;
    if (data.users.length < 1000) break;
  }

  return null;
}

async function sendSetupLink(
  serviceClient: ServiceClient,
  actorId: string,
  userId: string,
  email: string,
  displayName: string,
  role: string,
) {
  const setupUrl = passwordSetupUrl();
  const { data: linkData, error: linkError } = await serviceClient.auth.admin.generateLink({
    type: "recovery",
    email,
  });

  if (linkError || !linkData?.properties?.hashed_token) {
    throw linkError ?? new Error("Password setup link could not be generated");
  }

  const actionLink = buildPasswordSetupLink(setupUrl, linkData.properties.hashed_token);
  const subject = "Mitra Auto CMS account setup";
  const text = [
    "Mitra Auto CMS account",
    "",
    `Your CMS account has been created with role: ${role}`,
    "",
    "Use this link to set your password and open the CMS:",
    actionLink,
    "",
    "If you were not expecting this account, contact Mitra Auto immediately.",
  ].join("\n");

  await sendGmailRawEmail({
    toEmail: email,
    toName: displayName,
    subject,
    text,
    html: buildSetupEmailHtml(actionLink, role),
  });

  await serviceClient.from("cms_account_events").insert({
    target_profile_id: userId,
    actor_id: actorId,
    event_type: "staff_account_setup_link_sent",
    details: { email, role, provider: "gmail" },
  });
}

async function ensureAccountManager(request: Request) {
  const authHeader = request.headers.get("Authorization");
  if (!authHeader) {
    throw new Error("Missing Authorization header");
  }

  const userClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    { global: { headers: { Authorization: authHeader } } },
  );

  const { data: { user }, error: userError } = await userClient.auth.getUser();
  if (userError || !user) {
    throw new Error("Unauthenticated");
  }

  const { data: canManageAccounts, error: permissionError } = await userClient.rpc("cms_has_permission", {
    p_module: "accounts",
    p_action: "write",
  });

  if (permissionError || canManageAccounts !== true) {
    throw new Error("Forbidden");
  }

  const { data: accessRows, error: accessError } = await userClient.rpc("cms_get_current_access");
  const accessRow = Array.isArray(accessRows) ? accessRows[0] : null;
  if (accessError || !accessRow) {
    throw new Error("Forbidden");
  }

  return {
    user,
    isSuperAdmin: accessRow.role === "super_admin" && accessRow.account_status === "active",
  };
}

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (request.method !== "POST") {
    return jsonResponse({ error: "Method not allowed" }, 405);
  }

  try {
    const actorAccess = await ensureAccountManager(request);
    const actor = actorAccess.user;
    const body = await request.json().catch(() => ({}));
    const email = normalizeText(body?.email).toLowerCase();
    const action = normalizeText(body?.action) || "create";
    const requestedRole = normalizeRole(body?.role);
    const role = actorAccess.isSuperAdmin ? requestedRole : "supervisor";
    const displayName = normalizeText(body?.displayName);
    const permissions = actorAccess.isSuperAdmin
      ? normalizePermissions(body?.permissions)
      : defaultPermissionsForRole(role);

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return jsonResponse({ error: "Valid email is required" }, 400);
    }

    const serviceClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false, autoRefreshToken: false } },
    );

    if (action === "send_setup_link") {
      const userId = await findAuthUserIdByEmail(serviceClient, email);
      if (!userId) {
        return jsonResponse({ error: "Auth user not found" }, 400);
      }

      const { data: profile, error: profileError } = await serviceClient
        .from("profiles")
        .select("id, role, account_status, display_name")
        .eq("id", userId)
        .maybeSingle();

      if (profileError) {
        return jsonResponse({ error: profileError.message }, 400);
      }

      if (!profile?.id || profile.account_status === "deleted") {
        return jsonResponse({ error: "Active CMS profile not found for this account" }, 400);
      }

      await sendSetupLink(
        serviceClient,
        actor.id,
        userId,
        email,
        normalizeText(profile.display_name) || displayName,
        normalizeRole(profile.role),
      );

      return jsonResponse({ ok: true, userId, setupEmailSent: true });
    }

    const { data: createData, error: createError } = await serviceClient.auth.admin.createUser({
      email,
      password: temporaryPassword(),
      email_confirm: true,
      user_metadata: { display_name: displayName, cms_role: role },
    });

    let userId = createData.user?.id ?? null;
    let eventType = "staff_account_created";

    if (createError) {
      const message = createError.message || "";
      const isExistingUser = /already|registered|exists/i.test(message);
      if (!isExistingUser) {
        return jsonResponse({ error: message || "Failed to create auth user" }, 400);
      }

      userId = await findAuthUserIdByEmail(serviceClient, email);
      eventType = "staff_account_attached_existing_auth_user";
    }

    if (!userId) {
      return jsonResponse({ error: "Auth user was created but could not be resolved by email" }, 400);
    }

    const { error: profileError } = await serviceClient
      .from("profiles")
      .upsert({
        id: userId,
        role,
        display_name: displayName || null,
        cms_permissions: permissions,
        account_status: "active",
        account_hidden: false,
        updated_at: new Date().toISOString(),
      }, { onConflict: "id" });

    if (profileError) {
      return jsonResponse({ error: profileError.message }, 400);
    }

    await serviceClient.from("cms_account_events").insert({
      target_profile_id: userId,
      actor_id: actor.id,
      event_type: eventType,
      details: { email, role },
    });

    return jsonResponse({ ok: true, userId, existingUser: eventType !== "staff_account_created", setupEmailSent: false });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Invite failed";
    const status = message === "Unauthenticated" ? 401 : message === "Forbidden" ? 403 : 400;
    return jsonResponse({ error: message }, status);
  }
});
